[package]
name = "snacc-cli"
version = "0.1.0"
edition = "2024"

[package.metadata.bundle]
name = "snacc"
identifier = "com.snacc.cli"
version = "0.1.1"
short_description = "Snacc CLI"
long_description = "A tool that copies and organizes Kaggle notebooks and prints project trees."

[dependencies]
snacc-lib = { path = "../snacc-lib" }