name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./snacc-cli

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install GTK
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev

      - name: Install cargo-bundle
        run: cargo install cargo-bundle

      - name: Build .deb
        run: |
          cargo bundle --release --format deb
          mkdir -p ../dist
          cp target/release/bundle/deb/*.deb ../dist/snacc-installer-linux.deb

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-artifact
          path: ../dist/snacc-installer-linux.deb

  build-macos:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./snacc-cli

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install deps and cargo-bundle
        run: |
          brew install pkg-config
          cargo install cargo-bundle

      - name: Build .app
        run: |
          cargo bundle --release --format osx
          mkdir -p ../dist
          cp -R target/release/bundle/osx/snacc.app ../dist/snacc-macos.app
          ditto -c -k --sequesterRsrc --keepParent ../dist/snacc-macos.app ../dist/snacc-macos.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-artifact
          path: ../dist/snacc-macos.zip

  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./snacc-cli

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-wix
        run: cargo install cargo-wix

      - name: Generate .wxs if needed
        run: |
          if (-not (Test-Path "wix/main.wxs")) {
            cargo wix init
          }

      - name: Build .msi
        run: cargo wix

      - name: Zip executable
        run: |
          mkdir ../dist
          Compress-Archive -Path target/release/snacc.exe -DestinationPath ../dist/snacc-windows.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-artifact
          path: |
            ../dist/snacc-windows.zip
            target/wix/*.msi

  upload:
    needs: [build-linux, build-macos, build-windows]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./dist

      - name: Upload release artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**/*

