name: Release CLI

on:
  push:
    tags:
      - '*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./snacc-cli
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-bundle dependency
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev

      - name: Install cargo-bundle
        run: cargo install cargo-bundle

      - name: Build .deb installer
        run: |
          cargo bundle --release --format deb
          mkdir -p ../dist
          cp target/release/bundle/deb/*.deb ../dist/snacc-installer-linux.deb

      - name: Zip CLI binary
        run: |
          zip -j ../dist/snacc-linux.zip target/release/snacc

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: cli-linux
          path: ../dist/*

  build-macos:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./snacc-cli
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies and cargo-bundle
        run: |
          brew install pkg-config
          cargo install cargo-bundle

      - name: Build .app bundle
        run: |
          cargo bundle --release --format osx
          mkdir -p ../dist
          cp -R target/release/bundle/osx/snacc.app ../dist/snacc-macos.app
          ditto -c -k --sequesterRsrc --keepParent ../dist/snacc-macos.app ../dist/snacc-macos.zip

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: cli-macos
          path: ../dist/*

  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./snacc-cli
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-wix
        run: cargo install cargo-wix

      - name: Generate .wxs if needed
        run: |
          if (-not (Test-Path "wix/main.wxs")) {
            cargo wix init
          }

      - name: Build .msi
        run: cargo wix

      - name: Build release binary
        run: cargo build --release

      - name: Collect Windows artifacts
        run: |
          mkdir ../dist
          $msi = Get-ChildItem -Path target/wix -Filter *.msi | Select-Object -First 1
          Copy-Item $msi.FullName ../dist/snacc-installer-windows.msi
          Compress-Archive -Path target/release/snacc.exe -DestinationPath ../dist/snacc-windows.zip

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: cli-windows
          path: ../dist/*

  upload-release:
    needs: [build-linux, build-macos, build-windows]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./dist

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**/*

