name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-rust@v1
      - name: Install dependencies
        run: sudo apt update && sudo apt install -y libgtk-3-dev
      - name: Build Linux binary
        run: cargo build --release
      - name: Bundle as .deb
        run: cargo bundle --release --format deb
      - name: Rename and move
        run: |
          mkdir -p dist
          cp target/release/bundle/deb/*.deb dist/snacc-installer-linux.deb
      - uses: actions/upload-artifact@v4
        with:
          name: snacc-linux
          path: dist/snacc-installer-linux.deb

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-rust@v1
      - name: Install cargo-wix
        run: cargo install cargo-wix
      - name: Generate .wxs
        run: cargo wix init
      - name: Build .msi
        run: cargo wix
      - name: Rename and move
        run: |
          mkdir dist
          $msi = Get-ChildItem -Path target/wix -Filter *.msi | Select-Object -First 1
          Copy-Item $msi.FullName -Destination dist/snacc-installer-windows.msi
      - uses: actions/upload-artifact@v4
        with:
          name: snacc-windows
          path: dist/snacc-installer-windows.msi

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-rust@v1
      - name: Install dependencies
        run: brew install pkg-config gtk+3
      - name: Build macOS binary
        run: cargo build --release
      - name: Bundle as .app
        run: cargo bundle --release --format osx
      - name: Create .dmg from .app
        run: |
          mkdir -p dmg-tmp
          cp -R target/release/bundle/osx/snacc.app dmg-tmp/
          hdiutil create dist/snacc-installer-macos.dmg -volname snacc -srcfolder dmg-tmp -ov -format UDZO
      - uses: actions/upload-artifact@v4
        with:
          name: snacc-macos
          path: dist/snacc-installer-macos.dmg
