name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-bundle dependency
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev

      - name: Build .deb with cargo-bundle
        run: |
          cargo install cargo-bundle
          cargo bundle --release --format deb
          mkdir -p dist
          cp target/release/bundle/deb/*.deb dist/snacc-installer-linux.deb

      - name: Zip release binary
        run: |
          zip -j dist/snacc-linux.zip target/release/snacc

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-artifact
          path: |
            dist/snacc-installer-linux.deb
            dist/snacc-linux.zip

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build .app with cargo-bundle
        run: |
          brew install pkg-config
          cargo install cargo-bundle
          cargo bundle --release --format osx
          mkdir -p dist
          cp -R target/release/bundle/osx/snacc.app dist/snacc-macos.app

      - name: Zip .app directory
        run: |
          ditto -c -k --sequesterRsrc --keepParent dist/snacc-macos.app dist/snacc-macos.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-artifact
          path: |
            dist/snacc-macos.zip

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-wix
        run: cargo install cargo-wix

      - name: Generate .wxs if needed
        run: |
          if (-not (Test-Path "wix/main.wxs")) {
            cargo wix init
          }

      - name: Build .msi with cargo-wix
        run: cargo wix

      - name: Build release binary (.exe)
        run: cargo build --release

      - name: Copy artifacts (.msi and .zip)
        run: |
          mkdir dist

          # Copy the MSI
          $msi = Get-ChildItem -Path target/wix -Filter *.msi | Select-Object -First 1
          if ($msi -eq $null) {
            Write-Error "❌ MSI not found. cargo wix may have failed."
            exit 1
          }
          Copy-Item $msi.FullName dist/snacc-installer-windows.msi

          # Copy the .exe into a zip
          Compress-Archive -Path target/release/snacc.exe -DestinationPath dist/snacc-windows.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-artifact
          path: |
            dist/snacc-installer-windows.msi
            dist/snacc-windows.zip

  upload:
    needs: [build-linux, build-macos, build-windows]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./dist

      - name: Upload release artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**/*
