name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-deb (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: cargo install cargo-deb

      - name: Install cargo-wix (Windows)
        if: matrix.os == 'windows-latest'
        run: cargo install cargo-wix

      - name: Build Linux .deb
        if: matrix.os == 'ubuntu-latest'
        run: cargo deb

      - name: Build Windows .msi
        if: matrix.os == 'windows-latest'
        run: cargo wix

      - name: Build macOS binary
        if: matrix.os == 'macos-latest'
        run: cargo build --release

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-build
          path: |
            target/release/*.exe
            target/release/*.msi
            target/release/*.deb
            target/release/*