name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-bundle dependency
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev

      - name: Build .deb with cargo-bundle
        run: |
          cargo install cargo-bundle
          cargo bundle --release --format deb
          mkdir -p dist
          cp target/release/bundle/deb/*.deb dist/snacc-installer-linux.deb

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-artifact
          path: dist/

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build .app with cargo-bundle
        run: |
          brew install pkg-config
          cargo install cargo-bundle
          cargo bundle --release --format osx
          mkdir -p dist
          ditto -c -k --sequesterRsrc --keepParent target/release/bundle/osx/snacc.app dist/snacc-installer-macos.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-artifact
          path: dist/

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-wix
        run: cargo install cargo-wix

      - name: Generate .wxs if needed
        run: |
          if (-not (Test-Path "wix/main.wxs")) {
            cargo wix init
          }

      - name: Build .msi with cargo-wix
        run: cargo wix

      - name: Copy MSI to dist
        run: |
          mkdir dist
          $msi = Get-ChildItem -Path target/wix -Filter *.msi | Select-Object -First 1
          if ($msi -eq $null) {
            Write-Error "❌ MSI not found. cargo wix may have failed."
            exit 1
          }
          Copy-Item $msi.FullName dist/snacc-installer-windows.msi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-artifact
          path: dist/

  upload:
    needs: [build-linux, build-macos, build-windows]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: linux-artifact
          path: dist/linux

      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: macos-artifact
          path: dist/macos

      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-artifact
          path: dist/windows

      - name: Rename all installers to final names
        run: |
          mkdir -p dist/final
          cp dist/linux/*.deb dist/final/snacc-installer-linux.deb
          cp dist/macos/*.zip dist/final/snacc-installer-macos.zip
          cp dist/windows/*.msi dist/final/snacc-installer-windows.msi

      - name: Upload release artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: dist/final/snacc-installer-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
