name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-bundle dependency
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev

      - name: Build .deb with cargo-bundle
        run: |
          cargo install cargo-bundle
          cargo bundle --release --format deb
          mkdir -p dist
          cp target/release/bundle/deb/*.deb dist/snacc-installer-linux.deb

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build .app with cargo-bundle
        run: |
          brew install pkg-config
          cargo install cargo-bundle
          cargo bundle --release --format osx
          mkdir -p dist
          cd target/release/bundle/osx
          zip -r ../../../dist/snacc-installer-macos.zip snacc.app

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-wix
        run: cargo install cargo-wix

      - name: Generate .wxs if needed
        run: |
          if (-not (Test-Path "wix/main.wxs")) {
            cargo wix init
          }

      - name: Build .msi with cargo-wix
        run: cargo wix

      - name: Copy MSI to dist
        run: |
          mkdir dist
          $msi = Get-ChildItem -Path target/wix -Filter *.msi | Select-Object -First 1
          if ($msi -eq $null) {
            Write-Error "❌ MSI not found. cargo wix may have failed."
            exit 1
          }
          Copy-Item $msi.FullName dist/snacc-installer-windows.msi

  upload:
    needs: [build-linux, build-macos, build-windows]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./dist

      - name: Upload release artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: dist/snacc-installer-*
