name: Build and Release Installers

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build installers
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-deb (Linux)
        if: runner.os == 'Linux'
        run: cargo install cargo-deb

      - name: Build .deb package
        if: runner.os == 'Linux'
        run: |
          cargo deb
          mkdir -p dist
          cp target/debian/*.deb dist/snacc-installer-linux.deb

      - name: Install cargo-wix (Windows)
        if: runner.os == 'Windows'
        run: cargo install cargo-wix

      - name: Build .msi package
        if: runner.os == 'Windows'
        run: |
          cargo wix --force
          mkdir -p dist
          cp target/wix/*.msi dist/snacc-installer-windows.msi

      - name: Install cargo-bundle (macOS)
        if: runner.os == 'macOS'
        run: cargo install cargo-bundle

      - name: Build .app bundle (macOS)
        if: runner.os == 'macOS'
        run: |
          cargo bundle --release
          mkdir -p dist
          cp -R target/release/bundle/osx/snacc.app dist/snacc-installer-macos.app

      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: installers
          path: dist/

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: installers
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
