name: Build and Release Installers

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build installers
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt update && sudo apt install -y libwebkit2gtk-4.0-dev build-essential curl wget libssl-dev libgtk-3-dev squashfs-tools libayatana-appindicator3-dev librsvg2-dev

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          rustup component add rustfmt
          cargo install cargo-wix
          cargo install cargo-bundle

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install pkg-config cairo pango libpng jpeg giflib librsvg
          cargo install cargo-bundle

      - name: Build Debian (.deb)
        if: runner.os == 'Linux'
        run: |
          cargo install cargo-deb
          cargo deb
          mkdir -p dist
          cp target/debian/*.deb dist/snacc-installer-linux.deb

      - name: Build macOS (.app)
        if: runner.os == 'macOS'
        run: |
          cargo bundle --release
          mkdir -p dist
          cp -R target/release/bundle/osx/snacc.app dist/snacc-installer-macos.app

      - name: Build Windows (.msi)
        if: runner.os == 'Windows'
        run: |
          cargo wix --force
          mkdir -p dist
          cp target/wix/*.msi dist/snacc-installer-windows.msi

      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: installers
          path: dist/

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: installers
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
