name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-deb
        run: cargo install cargo-deb

      - name: Build .deb
        run: |
          cargo build --release
          cargo deb
          mkdir -p dist
          cp target/debian/*.deb dist/snacc-installer-linux.deb

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install pkgbuild tools
        run: brew install pkgconf

      - name: Install cargo-bundle
        run: cargo install cargo-bundle

      - name: Build .pkg
        run: |
          cargo build --release
          cargo bundle --format pkg
          mkdir -p dist
          cp target/release/bundle/osx/*.pkg dist/snacc-installer-macos.pkg

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-wix
        run: cargo install cargo-wix

      - name: Clean old .wxs if needed
        run: |
          if (Test-Path wix/main.wxs) { Remove-Item wix/main.wxs }

      - name: Build .msi
        run: |
          cargo build --release
          cargo wix
          mkdir dist
          $msi = Get-ChildItem -Path target/wix -Filter *.msi | Select-Object -First 1
          if ($msi) {
            Copy-Item $msi.FullName dist/snacc-installer-windows.msi
          } else {
            Write-Error "❌ MSI not found. cargo wix may have failed."
          }

  upload:
    needs: [build-linux, build-macos, build-windows]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Upload release artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: dist/snacc-installer-*
