name: Build Installers

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build Installers
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt update && sudo apt install -y dpkg-dev

      - name: Install dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: brew install pkgconf

      - name: Install dependencies (Windows)
        if: matrix.os == 'windows-latest'
        run: cargo install cargo-wix

      - name: Build installer (.deb)
        if: matrix.os == 'ubuntu-latest'
        run: |
          cargo install cargo-deb
          cargo deb
          mkdir -p dist
          cp target/debian/*.deb dist/snacc-installer-linux.deb

      - name: Build installer (.msi)
        if: matrix.os == 'windows-latest'
        run: |
          cargo wix init || echo "Already initialized"
          cargo wix
          mkdir -p dist
          cp target/wix/*.msi dist/snacc-installer-windows.msi

      - name: Build installer (.pkg)
        if: matrix.os == 'macos-latest'
        run: |
          cargo install cargo-bundle
          cargo bundle --release --format pkg
          mkdir -p dist
          cp target/release/bundle/pkg/*.pkg dist/snacc-installer-macos.pkg

      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: installers-${{ matrix.os }}
          path: dist/*