name: Release

on:
  push:
    tags:
      - 'v*.*.*'  # e.g., v0.1.0

permissions:
  contents: write

jobs:
  build:
    name: Build and Release Binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            ext: ''
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            ext: '.exe'
          - os: macos-latest
            target: x86_64-apple-darwin
            ext: ''

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build release binary
        run: |
          cargo build --release --target ${{ matrix.target }}

      - name: Rename binary
        run: |
          mkdir -p dist
          cp target/${{ matrix.target }}/release/notebook_auto_copy${{ matrix.ext }} dist/notebook_auto_copy-${{ matrix.target }}${{ matrix.ext }}

      - name: Upload binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: notebook_auto_copy-${{ matrix.target }}
          path: dist/notebook_auto_copy-${{ matrix.target }}${{ matrix.ext }}

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Publish GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**/*
